"""
Analytics Village — Database Schema (village.db)
All tables, indexes, and views from the specification.
"""

VILLAGE_DDL = """
-- ══════════════════════════════════════════════════════════════
-- VILLAGE.DB — Master simulation database
-- Generated by the simulation engine. Read-only for students.
-- ══════════════════════════════════════════════════════════════

CREATE TABLE IF NOT EXISTS businesses (
    business_id      TEXT PRIMARY KEY,
    owner_id         TEXT NOT NULL,
    business_name    TEXT NOT NULL,
    business_type    TEXT NOT NULL,
    opened_day       INTEGER NOT NULL,
    location_zone    TEXT NOT NULL,
    episode_primary  INTEGER,
    is_active        INTEGER NOT NULL DEFAULT 1
);
CREATE INDEX IF NOT EXISTS idx_businesses_type ON businesses(business_type);

-- ──────────────────────────────────────────────────────────────
CREATE TABLE IF NOT EXISTS owners (
    owner_id             TEXT PRIMARY KEY,
    name                 TEXT NOT NULL,
    age                  INTEGER,
    background           TEXT,
    personality_traits   TEXT,  -- JSON array
    known_blind_spots    TEXT,  -- JSON array
    communication_style  TEXT,
    hidden_goal          TEXT,
    llm_persona_prompt   TEXT,
    created_at           TEXT NOT NULL
);

-- ──────────────────────────────────────────────────────────────
CREATE TABLE IF NOT EXISTS households (
    household_id         TEXT PRIMARY KEY,
    household_size       INTEGER NOT NULL,
    dwelling_type        TEXT NOT NULL,
    location_zone        TEXT NOT NULL,
    income_bracket       TEXT NOT NULL,
    weekly_budget_thb    REAL NOT NULL,
    budget_variance_pct  REAL NOT NULL,
    move_in_day          INTEGER NOT NULL,
    move_out_day         INTEGER,
    is_active            INTEGER NOT NULL DEFAULT 1,
    fridge_capacity_L    REAL NOT NULL,
    pantry_capacity_units REAL NOT NULL,
    freezer_capacity_L   REAL NOT NULL,
    price_sensitivity    REAL NOT NULL,
    routine_strength     REAL NOT NULL,
    health_orientation   REAL NOT NULL,
    brand_loyalty        REAL NOT NULL,
    stock_anxiety        REAL NOT NULL,
    social_timing        REAL NOT NULL,
    llm_temperature      REAL NOT NULL,
    persona_narrative    TEXT,
    created_at           TEXT NOT NULL
);
CREATE INDEX IF NOT EXISTS idx_households_zone ON households(location_zone);
CREATE INDEX IF NOT EXISTS idx_households_active ON households(is_active);
CREATE INDEX IF NOT EXISTS idx_households_income ON households(income_bracket);

-- ──────────────────────────────────────────────────────────────
CREATE TABLE IF NOT EXISTS skus (
    sku_id               TEXT PRIMARY KEY,
    business_id          TEXT NOT NULL,
    sku_name             TEXT NOT NULL,
    sku_name_th          TEXT,
    category             TEXT NOT NULL,
    subcategory          TEXT,
    unit_description     TEXT NOT NULL,
    shelf_life_days      INTEGER,
    storage_type         TEXT NOT NULL,
    unit_volume_L        REAL,
    unit_weight_kg       REAL,
    base_cost_thb        REAL NOT NULL,
    base_price_thb       REAL NOT NULL,
    is_elastic           INTEGER NOT NULL DEFAULT 0,
    is_impulse           INTEGER NOT NULL DEFAULT 0,
    typical_daily_consume_per_person REAL,
    typical_daily_consume_per_household REAL,
    is_active            INTEGER NOT NULL DEFAULT 1
);
CREATE INDEX IF NOT EXISTS idx_skus_business ON skus(business_id);
CREATE INDEX IF NOT EXISTS idx_skus_category ON skus(category);
CREATE INDEX IF NOT EXISTS idx_skus_perishable ON skus(shelf_life_days)
    WHERE shelf_life_days IS NOT NULL;

-- ──────────────────────────────────────────────────────────────
CREATE TABLE IF NOT EXISTS transactions (
    transaction_id       TEXT PRIMARY KEY,
    business_id          TEXT NOT NULL,
    household_id         TEXT NOT NULL,
    day                  INTEGER NOT NULL,
    day_of_week          TEXT NOT NULL,
    week_of_month        INTEGER NOT NULL,
    is_payday_week       INTEGER NOT NULL DEFAULT 0,
    total_value_thb      REAL NOT NULL,
    total_cost_thb       REAL NOT NULL,
    item_count           INTEGER NOT NULL,
    satisfaction         TEXT NOT NULL,
    satisfaction_score   REAL NOT NULL,
    visited_also         TEXT,  -- JSON array
    noticed_promotion    INTEGER NOT NULL DEFAULT 0,
    responded_to_promotion INTEGER NOT NULL DEFAULT 0,
    decision_type        TEXT NOT NULL,
    llm_reasoning        TEXT,
    budget_at_visit_thb  REAL NOT NULL,
    budget_pruned        INTEGER NOT NULL DEFAULT 0,
    created_at           TEXT NOT NULL
);
CREATE INDEX IF NOT EXISTS idx_transactions_business ON transactions(business_id);
CREATE INDEX IF NOT EXISTS idx_transactions_household ON transactions(household_id);
CREATE INDEX IF NOT EXISTS idx_transactions_day ON transactions(day);
CREATE INDEX IF NOT EXISTS idx_transactions_business_day ON transactions(business_id, day);
CREATE INDEX IF NOT EXISTS idx_transactions_satisfaction ON transactions(satisfaction);
CREATE INDEX IF NOT EXISTS idx_transactions_payday ON transactions(is_payday_week);

-- ──────────────────────────────────────────────────────────────
CREATE TABLE IF NOT EXISTS basket_items (
    item_id              TEXT PRIMARY KEY,
    transaction_id       TEXT NOT NULL,
    sku_id               TEXT NOT NULL,
    qty_wanted           INTEGER NOT NULL,
    qty_sold             INTEGER NOT NULL,
    unit_price_thb       REAL NOT NULL,
    unit_cost_thb        REAL NOT NULL,
    line_value_thb       REAL NOT NULL,
    promo_applied        INTEGER NOT NULL DEFAULT 0,
    promo_discount_pct   REAL,
    stockout_flag        INTEGER NOT NULL DEFAULT 0,
    partial_fill         INTEGER NOT NULL DEFAULT 0,
    substitution         INTEGER NOT NULL DEFAULT 0,
    substituted_for_sku  TEXT,
    unresolved_stockout  INTEGER NOT NULL DEFAULT 0,
    responded_to_promo   INTEGER NOT NULL DEFAULT 0,
    budget_pruned        INTEGER NOT NULL DEFAULT 0,
    storage_blocked      INTEGER NOT NULL DEFAULT 0
);
CREATE INDEX IF NOT EXISTS idx_basket_transaction ON basket_items(transaction_id);
CREATE INDEX IF NOT EXISTS idx_basket_sku ON basket_items(sku_id);
CREATE INDEX IF NOT EXISTS idx_basket_stockout ON basket_items(stockout_flag);
CREATE INDEX IF NOT EXISTS idx_basket_promo ON basket_items(promo_applied);
CREATE INDEX IF NOT EXISTS idx_basket_substitution ON basket_items(substitution);

-- ──────────────────────────────────────────────────────────────
CREATE TABLE IF NOT EXISTS resident_days (
    rd_id                TEXT PRIMARY KEY,
    household_id         TEXT NOT NULL,
    day                  INTEGER NOT NULL,
    lifecycle_state      TEXT NOT NULL,
    decision_type        TEXT NOT NULL,
    stores_visited       TEXT,  -- JSON array
    p_visit_score        REAL NOT NULL,
    llm_called           INTEGER NOT NULL DEFAULT 0,
    pantry_urgency       REAL NOT NULL,
    mood                 TEXT NOT NULL,
    mood_modifier        REAL NOT NULL,
    calendar_multiplier  REAL NOT NULL,
    received_winback_offer INTEGER NOT NULL DEFAULT 0,
    winback_offer_id     TEXT,
    word_of_mouth_spread INTEGER NOT NULL DEFAULT 0
);
CREATE UNIQUE INDEX IF NOT EXISTS idx_rd_household_day
    ON resident_days(household_id, day);
CREATE INDEX IF NOT EXISTS idx_rd_lifecycle ON resident_days(lifecycle_state);
CREATE INDEX IF NOT EXISTS idx_rd_decision ON resident_days(decision_type);
CREATE INDEX IF NOT EXISTS idx_rd_day ON resident_days(day);
CREATE INDEX IF NOT EXISTS idx_rd_llm_called ON resident_days(llm_called);

-- ──────────────────────────────────────────────────────────────
CREATE TABLE IF NOT EXISTS lifecycle_events (
    event_id             TEXT PRIMARY KEY,
    household_id         TEXT NOT NULL,
    business_id          TEXT NOT NULL,
    day                  INTEGER NOT NULL,
    from_state           TEXT NOT NULL,
    to_state             TEXT NOT NULL,
    trigger_type         TEXT NOT NULL,
    trigger_detail       TEXT,
    days_since_last_visit INTEGER,
    spend_last_21d_thb   REAL,
    stockout_count_30d   INTEGER,
    alt_visits_30d       INTEGER,
    campaign_id          TEXT
);
CREATE INDEX IF NOT EXISTS idx_lifecycle_household ON lifecycle_events(household_id);
CREATE INDEX IF NOT EXISTS idx_lifecycle_business ON lifecycle_events(business_id);
CREATE INDEX IF NOT EXISTS idx_lifecycle_day ON lifecycle_events(day);
CREATE INDEX IF NOT EXISTS idx_lifecycle_transition
    ON lifecycle_events(from_state, to_state);
CREATE INDEX IF NOT EXISTS idx_lifecycle_trigger ON lifecycle_events(trigger_type);

-- ──────────────────────────────────────────────────────────────
CREATE TABLE IF NOT EXISTS stock_ledger (
    ledger_id            TEXT PRIMARY KEY,
    business_id          TEXT NOT NULL,
    sku_id               TEXT NOT NULL,
    day                  INTEGER NOT NULL,
    shelf_open           INTEGER NOT NULL,
    warehouse_open       INTEGER NOT NULL,
    shelf_replenished    INTEGER NOT NULL DEFAULT 0,
    units_sold           INTEGER NOT NULL DEFAULT 0,
    units_expired        INTEGER NOT NULL DEFAULT 0,
    units_shrinkage      INTEGER NOT NULL DEFAULT 0,
    units_delivered      INTEGER NOT NULL DEFAULT 0,
    shelf_close          INTEGER NOT NULL,
    warehouse_close      INTEGER NOT NULL,
    total_stock_close    INTEGER NOT NULL,
    stockout_occurred    INTEGER NOT NULL DEFAULT 0,
    near_expiry_flag     INTEGER NOT NULL DEFAULT 0,
    near_expiry_units    INTEGER NOT NULL DEFAULT 0,
    reorder_triggered    INTEGER NOT NULL DEFAULT 0
);
CREATE UNIQUE INDEX IF NOT EXISTS idx_stock_biz_sku_day
    ON stock_ledger(business_id, sku_id, day);
CREATE INDEX IF NOT EXISTS idx_stock_stockout ON stock_ledger(stockout_occurred);
CREATE INDEX IF NOT EXISTS idx_stock_expiry ON stock_ledger(near_expiry_flag);

-- ──────────────────────────────────────────────────────────────
CREATE TABLE IF NOT EXISTS supply_events (
    event_id             TEXT PRIMARY KEY,
    business_id          TEXT NOT NULL,
    supplier_id          TEXT NOT NULL,
    po_id                TEXT NOT NULL,
    sku_id               TEXT NOT NULL,
    day_ordered          INTEGER NOT NULL,
    day_expected         INTEGER NOT NULL,
    day_delivered        INTEGER,
    qty_ordered          INTEGER NOT NULL,
    qty_delivered        INTEGER,
    unit_cost_thb        REAL NOT NULL,
    total_cost_thb       REAL NOT NULL,
    status               TEXT NOT NULL,
    fill_rate            REAL,
    is_backup_supplier   INTEGER NOT NULL DEFAULT 0,
    adaptive_price_applied INTEGER NOT NULL DEFAULT 0,
    adaptive_price_reason TEXT,
    warehouse_space_check INTEGER NOT NULL DEFAULT 0
);
CREATE INDEX IF NOT EXISTS idx_supply_business ON supply_events(business_id);
CREATE INDEX IF NOT EXISTS idx_supply_sku ON supply_events(sku_id);
CREATE INDEX IF NOT EXISTS idx_supply_status ON supply_events(status);
CREATE INDEX IF NOT EXISTS idx_supply_po ON supply_events(po_id);

-- ──────────────────────────────────────────────────────────────
CREATE TABLE IF NOT EXISTS suppliers (
    supplier_id          TEXT PRIMARY KEY,
    supplier_name        TEXT NOT NULL,
    reliability_score    REAL NOT NULL,
    base_lead_time_days  INTEGER NOT NULL,
    max_lead_time_days   INTEGER NOT NULL,
    min_order_qty        INTEGER NOT NULL DEFAULT 1,
    price_tier           TEXT NOT NULL,
    supplies_skus        TEXT NOT NULL,  -- JSON array
    is_backup            INTEGER NOT NULL DEFAULT 0,
    adaptive_price_threshold INTEGER NOT NULL DEFAULT 3
);

-- ──────────────────────────────────────────────────────────────
CREATE TABLE IF NOT EXISTS price_log (
    log_id               TEXT PRIMARY KEY,
    business_id          TEXT NOT NULL,
    sku_id               TEXT NOT NULL,
    day                  INTEGER NOT NULL,
    base_price_thb       REAL NOT NULL,
    sale_price_thb       REAL NOT NULL,
    cost_thb             REAL NOT NULL,
    margin_pct           REAL NOT NULL,
    promo_active         INTEGER NOT NULL DEFAULT 0,
    discount_pct         REAL,
    near_expiry_discount INTEGER NOT NULL DEFAULT 0,
    days_until_expiry    INTEGER,
    pricing_decision     TEXT NOT NULL,
    llm_reasoning        TEXT
);
CREATE UNIQUE INDEX IF NOT EXISTS idx_price_biz_sku_day
    ON price_log(business_id, sku_id, day);
CREATE INDEX IF NOT EXISTS idx_price_promo ON price_log(promo_active);
CREATE INDEX IF NOT EXISTS idx_price_margin ON price_log(margin_pct);

-- ──────────────────────────────────────────────────────────────
CREATE TABLE IF NOT EXISTS campaign_log (
    campaign_id          TEXT PRIMARY KEY,
    business_id          TEXT NOT NULL,
    day_launched         INTEGER NOT NULL,
    day_ended            INTEGER NOT NULL,
    campaign_type        TEXT NOT NULL,
    target_segment       TEXT NOT NULL,
    target_household_ids TEXT,  -- JSON array
    channel              TEXT NOT NULL,
    message_tone         TEXT NOT NULL,
    reach_pct            REAL NOT NULL,
    households_targeted  INTEGER NOT NULL,
    households_reached   INTEGER NOT NULL,
    households_responded INTEGER NOT NULL DEFAULT 0,
    response_rate        REAL,
    offer_type           TEXT,
    offer_value_thb      REAL,
    total_campaign_cost_thb REAL NOT NULL DEFAULT 0,
    incremental_revenue_thb REAL,
    roi                  REAL,
    llm_decision_reasoning TEXT
);
CREATE INDEX IF NOT EXISTS idx_campaign_business ON campaign_log(business_id);
CREATE INDEX IF NOT EXISTS idx_campaign_type ON campaign_log(campaign_type);
CREATE INDEX IF NOT EXISTS idx_campaign_day ON campaign_log(day_launched);

-- ──────────────────────────────────────────────────────────────
CREATE TABLE IF NOT EXISTS waste_events (
    waste_id             TEXT PRIMARY KEY,
    day                  INTEGER NOT NULL,
    actor_type           TEXT NOT NULL,
    actor_id             TEXT NOT NULL,
    sku_id               TEXT NOT NULL,
    qty_wasted           REAL NOT NULL,
    waste_reason         TEXT NOT NULL,
    estimated_cost_thb   REAL NOT NULL,
    days_held_before_waste INTEGER,
    triggered_satisfaction_drop INTEGER NOT NULL DEFAULT 0
);
CREATE INDEX IF NOT EXISTS idx_waste_actor ON waste_events(actor_type, actor_id);
CREATE INDEX IF NOT EXISTS idx_waste_sku ON waste_events(sku_id);
CREATE INDEX IF NOT EXISTS idx_waste_day ON waste_events(day);
CREATE INDEX IF NOT EXISTS idx_waste_reason ON waste_events(waste_reason);

-- ──────────────────────────────────────────────────────────────
CREATE TABLE IF NOT EXISTS capacity_log (
    log_id               TEXT PRIMARY KEY,
    day                  INTEGER NOT NULL,
    actor_type           TEXT NOT NULL,
    actor_id             TEXT NOT NULL,
    fridge_pct_full      REAL,
    pantry_pct_full      REAL,
    freezer_pct_full     REAL,
    weekly_budget_spent_pct REAL,
    shelf_pct_full       REAL,
    warehouse_pct_full   REAL,
    cold_storage_pct_full REAL,
    po_budget_used_pct   REAL,
    po_budget_overrun    INTEGER NOT NULL DEFAULT 0,
    staff_restock_cap_hit INTEGER NOT NULL DEFAULT 0
);
CREATE INDEX IF NOT EXISTS idx_capacity_actor
    ON capacity_log(actor_type, actor_id, day);
CREATE INDEX IF NOT EXISTS idx_capacity_day ON capacity_log(day);

-- ──────────────────────────────────────────────────────────────
CREATE TABLE IF NOT EXISTS store_metrics (
    metric_id            TEXT PRIMARY KEY,
    business_id          TEXT NOT NULL,
    day                  INTEGER NOT NULL,
    unique_visitors      INTEGER NOT NULL DEFAULT 0,
    new_acquisitions     INTEGER NOT NULL DEFAULT 0,
    active_customers_30d INTEGER NOT NULL DEFAULT 0,
    retained_count       INTEGER NOT NULL DEFAULT 0,
    at_risk_count        INTEGER NOT NULL DEFAULT 0,
    churned_count        INTEGER NOT NULL DEFAULT 0,
    winback_sent_today   INTEGER NOT NULL DEFAULT 0,
    winback_accepted_today INTEGER NOT NULL DEFAULT 0,
    gross_revenue_thb    REAL NOT NULL DEFAULT 0,
    gross_margin_thb     REAL NOT NULL DEFAULT 0,
    avg_basket_value_thb REAL,
    avg_items_per_basket REAL,
    stockout_incidents   INTEGER NOT NULL DEFAULT 0,
    stockout_rate        REAL NOT NULL DEFAULT 0,
    waste_value_thb      REAL NOT NULL DEFAULT 0,
    po_budget_remaining_thb REAL,
    village_total_households INTEGER NOT NULL,
    village_active_households INTEGER NOT NULL
);
CREATE UNIQUE INDEX IF NOT EXISTS idx_metrics_biz_day
    ON store_metrics(business_id, day);
CREATE INDEX IF NOT EXISTS idx_metrics_day ON store_metrics(day);

-- ──────────────────────────────────────────────────────────────
CREATE TABLE IF NOT EXISTS reviews (
    review_id            TEXT PRIMARY KEY,
    business_id          TEXT NOT NULL,
    household_id         TEXT NOT NULL,
    day                  INTEGER NOT NULL,
    transaction_id       TEXT,
    text                 TEXT NOT NULL,
    language             TEXT NOT NULL,
    rating               INTEGER NOT NULL,
    satisfaction_at_visit TEXT,
    themes               TEXT,  -- JSON array
    sentiment_score      REAL,
    is_genuine           INTEGER NOT NULL DEFAULT 1
);
CREATE INDEX IF NOT EXISTS idx_reviews_business ON reviews(business_id);
CREATE INDEX IF NOT EXISTS idx_reviews_day ON reviews(day);
CREATE INDEX IF NOT EXISTS idx_reviews_rating ON reviews(rating);
CREATE INDEX IF NOT EXISTS idx_reviews_language ON reviews(language);

-- ──────────────────────────────────────────────────────────────
CREATE TABLE IF NOT EXISTS alt_transactions (
    transaction_id       TEXT PRIMARY KEY,
    household_id         TEXT NOT NULL,
    business_id          TEXT NOT NULL,
    day                  INTEGER NOT NULL,
    total_value_thb      REAL NOT NULL,
    item_count           INTEGER NOT NULL,
    category_breakdown   TEXT NOT NULL,  -- JSON
    triggered_by         TEXT NOT NULL
);
CREATE INDEX IF NOT EXISTS idx_alt_household ON alt_transactions(household_id);
CREATE INDEX IF NOT EXISTS idx_alt_business ON alt_transactions(business_id);
CREATE INDEX IF NOT EXISTS idx_alt_day ON alt_transactions(day);
CREATE INDEX IF NOT EXISTS idx_alt_trigger ON alt_transactions(triggered_by);

-- ──────────────────────────────────────────────────────────────
CREATE TABLE IF NOT EXISTS profile_snapshots (
    snapshot_id          TEXT PRIMARY KEY,
    week                 INTEGER NOT NULL,
    agent_type           TEXT NOT NULL,
    agent_id             TEXT NOT NULL,
    profile_narrative    TEXT NOT NULL,
    key_changes          TEXT,  -- JSON array
    lifecycle_state      TEXT,
    satisfaction_trend   TEXT,
    llm_reasoning        TEXT,
    trigger_events       TEXT   -- JSON array
);
CREATE INDEX IF NOT EXISTS idx_snapshots_agent
    ON profile_snapshots(agent_type, agent_id);
CREATE INDEX IF NOT EXISTS idx_snapshots_week ON profile_snapshots(week);

-- ──────────────────────────────────────────────────────────────
CREATE TABLE IF NOT EXISTS village_roster (
    roster_id            TEXT PRIMARY KEY,
    household_id         TEXT NOT NULL,
    day                  INTEGER NOT NULL,
    event_type           TEXT NOT NULL,
    lifecycle_state      TEXT NOT NULL,
    days_in_village      INTEGER NOT NULL,
    total_spend_all_stores_thb REAL NOT NULL DEFAULT 0,
    primary_store        TEXT
);
CREATE INDEX IF NOT EXISTS idx_roster_day ON village_roster(day);
CREATE INDEX IF NOT EXISTS idx_roster_household ON village_roster(household_id);
CREATE INDEX IF NOT EXISTS idx_roster_event ON village_roster(event_type);

-- ──────────────────────────────────────────────────────────────
CREATE TABLE IF NOT EXISTS event_ledger (
    event_id             TEXT PRIMARY KEY,
    day                  INTEGER NOT NULL,
    timestamp_ms         INTEGER NOT NULL,
    event_type           TEXT NOT NULL,
    actor_type           TEXT NOT NULL,
    actor_id             TEXT NOT NULL,
    target_type          TEXT,
    target_id            TEXT,
    payload              TEXT NOT NULL  -- JSON blob
);
CREATE INDEX IF NOT EXISTS idx_ledger_day ON event_ledger(day);
CREATE INDEX IF NOT EXISTS idx_ledger_type ON event_ledger(event_type);
CREATE INDEX IF NOT EXISTS idx_ledger_actor ON event_ledger(actor_type, actor_id);

-- ──────────────────────────────────────────────────────────────
CREATE TABLE IF NOT EXISTS calendar_events (
    cal_id               TEXT PRIMARY KEY,
    day                  INTEGER NOT NULL,
    event_name           TEXT NOT NULL,
    event_type           TEXT NOT NULL,
    demand_multiplier    REAL NOT NULL DEFAULT 1.0,
    category_effects     TEXT  -- JSON
);
CREATE INDEX IF NOT EXISTS idx_calendar_day ON calendar_events(day);
CREATE INDEX IF NOT EXISTS idx_calendar_type ON calendar_events(event_type);

-- ──────────────────────────────────────────────────────────────
-- Hidden table for anomaly detection episodes (EP08)
CREATE TABLE IF NOT EXISTS _anomaly_log (
    anomaly_id           TEXT PRIMARY KEY,
    business_id          TEXT NOT NULL,
    anomaly_type         TEXT NOT NULL,
    actor_description    TEXT NOT NULL,
    affected_day_range   TEXT NOT NULL,  -- JSON [start, end]
    affected_skus        TEXT,           -- JSON array
    pattern_description  TEXT NOT NULL,
    financial_impact_thb REAL NOT NULL,
    is_active            INTEGER NOT NULL DEFAULT 1
);

-- ──────────────────────────────────────────────────────────────
-- Simulation metadata (config, checkpoints)
CREATE TABLE IF NOT EXISTS _simulation_meta (
    key   TEXT PRIMARY KEY,
    value TEXT NOT NULL
);

-- ══════════════════════════════════════════════════════════════
-- VIEWS — Pre-built for student convenience
-- ══════════════════════════════════════════════════════════════

CREATE VIEW IF NOT EXISTS v_customer_summary AS
SELECT
    h.household_id,
    h.household_size,
    h.income_bracket,
    h.location_zone,
    le.lifecycle_state,
    COUNT(DISTINCT t.transaction_id) AS total_visits,
    SUM(t.total_value_thb) AS total_spend_thb,
    AVG(t.total_value_thb) AS avg_basket_thb,
    MAX(t.day) AS last_visit_day,
    MIN(t.day) AS first_visit_day,
    AVG(t.satisfaction_score) AS avg_satisfaction,
    SUM(t.responded_to_promotion) AS promo_responses
FROM households h
LEFT JOIN transactions t ON h.household_id = t.household_id
    AND t.business_id = 'supermarket'
LEFT JOIN (
    SELECT household_id, lifecycle_state,
           ROW_NUMBER() OVER (
               PARTITION BY household_id ORDER BY day DESC
           ) AS rn
    FROM lifecycle_events
    WHERE business_id = 'supermarket'
) le ON h.household_id = le.household_id AND le.rn = 1
GROUP BY h.household_id;

CREATE VIEW IF NOT EXISTS v_daily_revenue AS
SELECT
    t.business_id,
    t.day,
    t.day_of_week,
    t.is_payday_week,
    COUNT(DISTINCT t.transaction_id) AS transactions,
    COUNT(DISTINCT t.household_id) AS unique_customers,
    SUM(t.total_value_thb) AS revenue_thb,
    SUM(t.total_cost_thb) AS cost_thb,
    SUM(t.total_value_thb) - SUM(t.total_cost_thb) AS margin_thb,
    AVG(t.total_value_thb) AS avg_basket_thb
FROM transactions t
GROUP BY t.business_id, t.day;

CREATE VIEW IF NOT EXISTS v_stockout_impact AS
SELECT
    bi.sku_id,
    s.sku_name,
    COUNT(*) AS stockout_events,
    SUM(bi.qty_wanted - bi.qty_sold) AS units_lost,
    SUM((bi.qty_wanted - bi.qty_sold) * bi.unit_price_thb) AS revenue_lost_thb,
    COUNT(DISTINCT bi.transaction_id) AS customers_affected
FROM basket_items bi
JOIN skus s ON bi.sku_id = s.sku_id
WHERE bi.stockout_flag = 1
GROUP BY bi.sku_id, s.sku_name
ORDER BY revenue_lost_thb DESC;
"""


def create_village_db(path: str) -> None:
    """Create a new village.db with all tables, indexes, and views."""
    import sqlite3

    conn = sqlite3.connect(path)
    conn.executescript(VILLAGE_DDL)
    conn.commit()
    conn.close()
